api_platform:
    title: "Min's tale's"
    description: 'Api rest of application mins tales'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorize
                type: header
